# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      # 'main' branch: PRD environment
      - template: ../../config-infra-prod.yml
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      # 'develop' or feature branches: DEV environment
      - template: ../../config-infra-dev.yml
  - name: version
    value: aml-cli-v2

trigger:
  - none

pool:
  vmImage: ubuntu-20.04

stages:
  - stage: DeployTrainingPipeline
    displayName: Deploy Training Pipeline
    jobs:
      - job: DeployTrainingPipeline
        timeoutInMinutes: 120 # how long to run the job before automatically cancelling
        steps:

          - template: ../../templates/${{ variables.version }}/install-az-cli.yml
          - template: ../../templates/${{ variables.version }}/install-aml-cli.yml
          - template: ../../templates/${{ variables.version }}/connect-to-workspace.yml
          - template: ../../templates/${{ variables.version }}/register-environment.yml
            parameters:
              environment_name: taxi-train-env
              environment_file: mlops/azureml/train/train-env.yml
          - template: ../../templates/${{ variables.version }}/create-compute.yml
            parameters:
              cluster_name: cpu-cluster
              size: Standard_DS2_v2
              min_instances: 0
              max_instances: 4
              cluster_tier: low_priority
          - template: ../../templates/${{ variables.version }}/register-data.yml
            parameters:
              data_type: uri_file
              data_name: taxi-data
              data_file: mlops/azureml/train/data.yml
          - template: ../../templates/${{ variables.version }}/run-pipeline.yml
            parameters:
              pipeline_file: mlops/azureml/train/pipeline.yml
              experiment_name: $(environment)_taxi_fare_train_$(Build.SourceBranchName)
              display_name: $(environment)_taxi_fare_run_$(Build.BuildID)
              enable_monitoring: $(enable_monitoring)
